#!/bin/bash

shopt -s extglob

#Parameters for SeqVItA varaint calling
min_coverage=10;                               # Minimum coverage for variant calling
min_reads2=2;                                 # Minimum number of reads that should support variant
min_avg_qual=15;                              # Minimum base quality ata position to consider it for variant calling
min_var_freq=0.20;                            # Minimum Variant allele frequency for variant calling
min_freq_for_hom=0.75;                        # Minimum Variant allele frequency for a variant to be Homozygous
p_value=0.01;                                 # P-value threshold bwlow which variant is called
strand_filter=1;                              # Strand filter to filter variant with >90% or < 10% from one strand
mapping_quality=20;
mq_adjustment=0;
somatic_p_value=0.05

# Required Options

input_file="";
reference_file="";
output_file="";
variant_calling_type="";
bam_file="";
bamfiles=( )
bed_file=""
normal_file="";
tumor_file="";

SOURCEDIR=$(dirname $(readlink -f $0))


while [ -n "$1" ]
do
  case "$1" in
    -v) variant_calling_type="$2"
    shift;;
    -ib) inputfiles+=( "$2" )
    shift;;
    -im) input_file+="$2"
    shift;;
    -normal) normal_file="$2"
    shift;;
    -tumor) tumor_file="$2"
    shift;;
    -r) reference_file="$2"
    shift;;
    -bed) bed_file="$2"
    shift;;
    --Mqread) mapping_quality="$2"
    shift;;
    --Mqcorr) mq_adjustment="$2"
    shift;;
    --RD_th) min_coverage="$2"
    shift;;
    --VAR_th) min_reads2="$2"
    shift;;
    --Qbase) min_avg_qual="$2"
    shift;;
    --VAF_th) min_var_freq="$2"
    shift;;
    --VAF_homo) min_freq_for_hom="$2"
    shift;;
    --p-value) p_value="$2"
    shift;;
    --somatic-p-value) somatic_p_value="$2"
    shift;;
    --Strand_Bias) strand_filter="$2"
    shift;;
    -o) output_file="$2"
    shift;;
    *) inputfiles+=( "$1" );;
  esac
  shift
done
for inp in "${inputfiles[@]}";
do
  bam_file+="$inp "
done

if [[ $reference_file != "" && $bed_file != "" ]]; then
  if [[ $normal_file != "" && $tumor_file != "" ]]; then
    samtools mpileup -f $reference_file -B -q $mapping_quality -C $mq_adjustment $normal_file $tumor_file --positions $bed_file > $output_file.mpileup
    $SOURCEDIR/seqvita $variant_calling_type ./$output_file.mpileup --min-coverage $min_coverage --min-reads2 $min_reads2 --min-avg-qual $min_avg_qual --min-var-freq $min_var_freq --min-freq-for-hom $min_freq_for_hom --p-value $p_value --somatic-p-value $somatic_p_value --strand-filter $strand_filter > $output_file.vcf
  else
    samtools mpileup -f $reference_file -B -q $mapping_quality -C $mq_adjustment $bam_file --positions $bed_file > $output_file.mpileup
    $SOURCEDIR/seqvita $variant_calling_type ./$output_file.mpileup --min-coverage $min_coverage --min-reads2 $min_reads2 --min-avg-qual $min_avg_qual --min-var-freq $min_var_freq --min-freq-for-hom $min_freq_for_hom --p-value $p_value --somatic-p-value $somatic_p_value --strand-filter $strand_filter > $output_file.vcf
  fi
elif [[ $reference_file != "" ]]; then
  if [[ $normal_file!="" && $tumor_file!="" ]]; then
    samtools mpileup -f $reference_file -B -q $mapping_quality -C $mq_adjustment$normal_file $tumor_file  > $output_file.mpileup
    $SOURCEDIR/seqvita $variant_calling_type ./$output_file.mpileup --min-coverage $min_coverage --min-reads2 $min_reads2 --min-avg-qual $min_avg_qual --min-var-freq $min_var_freq --min-freq-for-hom $min_freq_for_hom --p-value $p_value --somatic-p-value $somatic_p_value --strand-filter $strand_filter > $output_file.vcf
  else
    samtools mpileup -f $reference_file -B -B -q $mapping_quality -C $mq_adjustment $bam_file > $output_file.mpileup
    $SOURCEDIR/seqvita $variant_calling_type ./$output_file.mpileup --min-coverage $min_coverage --min-reads2 $min_reads2 --min-avg-qual $min_avg_qual --min-var-freq $min_var_freq --min-freq-for-hom $min_freq_for_hom --p-value $p_value --somatic-p-value $somatic_p_value --strand-filter $strand_filter > $output_file.vcf
  fi
else
  $SOURCEDIR/seqvita $variant_calling_type $input_file --min-coverage $min_coverage --min-reads2 $min_reads2 --min-avg-qual $min_avg_qual --min-var-freq $min_var_freq --min-freq-for-hom $min_freq_for_hom --p-value $p_value --somatic-p-value $somatic_p_value --strand-filter $strand_filter > $output_file.vcf
fi
